export const GET_ALL_ITEMS = "GET_ALL_ITEMS";
export const FILTER_ITEMS = "FILTER_ITEMS";
export const FILTER_FILTERED_ITEMS = "FILTER_FILTERED_ITEMS";


export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";
export const LOGOUT_USER = 'LOGOUT_USER';
export const SET_LOGGED_IN = "SET_LOGGED_IN";
